# {{.ProjectName}} Makefile
# Generated by go-ctl

# Variables
BINARY_NAME={{.ProjectName}}
MAIN_PATH=cmd/$(BINARY_NAME)/main.go
BUILD_DIR=bin
GO_VERSION={{.GoVersion}}

# Colors for output
RED=\033[0;31m
GREEN=\033[0;32m
YELLOW=\033[1;33m
BLUE=\033[0;34m
NC=\033[0m # No Color

# Default target
.DEFAULT_GOAL := help

# Help target
.PHONY: help
help: ## Show this help message
	@echo "$(BLUE)Available commands:$(NC)"
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  $(GREEN)%-15s$(NC) %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# Build targets
.PHONY: build
build: ## Build the application
	@echo "$(YELLOW)Building $(BINARY_NAME)...$(NC)"
	@mkdir -p $(BUILD_DIR)
	@go build -ldflags="-w -s" -o $(BUILD_DIR)/$(BINARY_NAME) $(MAIN_PATH)
	@echo "$(GREEN)Build completed: $(BUILD_DIR)/$(BINARY_NAME)$(NC)"

.PHONY: build-race
build-race: ## Build with race detection
	@echo "$(YELLOW)Building $(BINARY_NAME) with race detection...$(NC)"
	@mkdir -p $(BUILD_DIR)
	@go build -race -o $(BUILD_DIR)/$(BINARY_NAME)-race $(MAIN_PATH)
	@echo "$(GREEN)Build completed: $(BUILD_DIR)/$(BINARY_NAME)-race$(NC)"

# Development targets
.PHONY: run
run: ## Run the application
	@echo "$(YELLOW)Running $(BINARY_NAME)...$(NC)"
	@go run $(MAIN_PATH)

{{if .HasFeature "air"}}.PHONY: dev
dev: ## Run with hot reload (requires Air)
	@echo "$(YELLOW)Starting development server with hot reload...$(NC)"
	@air

.PHONY: dev-init
dev-init: ## Initialize Air configuration
	@echo "$(YELLOW)Initializing Air configuration...$(NC)"
	@air init
{{else}}.PHONY: dev
dev: run ## Alias for run (install Air for hot reload)
{{end}}

# Testing targets
.PHONY: test
test: ## Run tests
	@echo "$(YELLOW)Running tests...$(NC)"
	@go test ./...

.PHONY: test-verbose
test-verbose: ## Run tests with verbose output
	@echo "$(YELLOW)Running tests (verbose)...$(NC)"
	@go test -v ./...

.PHONY: test-cover
test-cover: ## Run tests with coverage
	@echo "$(YELLOW)Running tests with coverage...$(NC)"
	@go test -cover ./...

.PHONY: test-cover-html
test-cover-html: ## Generate HTML coverage report
	@echo "$(YELLOW)Generating HTML coverage report...$(NC)"
	@go test -coverprofile=coverage.out ./...
	@go tool cover -html=coverage.out -o coverage.html
	@echo "$(GREEN)Coverage report generated: coverage.html$(NC)"

.PHONY: benchmark
benchmark: ## Run benchmarks
	@echo "$(YELLOW)Running benchmarks...$(NC)"
	@go test -bench=. -benchmem ./...

# Code quality targets
.PHONY: fmt
fmt: ## Format code
	@echo "$(YELLOW)Formatting code...$(NC)"
	@go fmt ./...
	@echo "$(GREEN)Code formatted$(NC)"

.PHONY: vet
vet: ## Run go vet
	@echo "$(YELLOW)Running go vet...$(NC)"
	@go vet ./...
	@echo "$(GREEN)No issues found$(NC)"

.PHONY: lint
lint: ## Run golangci-lint (requires golangci-lint)
	@echo "$(YELLOW)Running golangci-lint...$(NC)"
	@golangci-lint run

.PHONY: tidy
tidy: ## Tidy dependencies
	@echo "$(YELLOW)Tidying dependencies...$(NC)"
	@go mod tidy
	@echo "$(GREEN)Dependencies tidied$(NC)"

.PHONY: verify
verify: ## Verify dependencies
	@echo "$(YELLOW)Verifying dependencies...$(NC)"
	@go mod verify
	@echo "$(GREEN)Dependencies verified$(NC)"

.PHONY: check
check: fmt vet test ## Run all checks (format, vet, test)

# Database targets
{{if ne .Database.ID ""}}{{if eq .Database.ID "postgres"}}.PHONY: db-create
db-create: ## Create PostgreSQL database
	@echo "$(YELLOW)Creating PostgreSQL database...$(NC)"
	@createdb {{.ProjectName}}_db || echo "$(YELLOW)Database may already exist$(NC)"

.PHONY: db-drop
db-drop: ## Drop PostgreSQL database
	@echo "$(RED)Dropping PostgreSQL database...$(NC)"
	@dropdb {{.ProjectName}}_db || echo "$(YELLOW)Database may not exist$(NC)"

.PHONY: db-reset
db-reset: db-drop db-create ## Reset PostgreSQL database
{{else if eq .Database.ID "mysql"}}.PHONY: db-create
db-create: ## Create MySQL database
	@echo "$(YELLOW)Creating MySQL database...$(NC)"
	@mysql -u root -p -e "CREATE DATABASE IF NOT EXISTS {{.ProjectName}}_db;"

.PHONY: db-drop
db-drop: ## Drop MySQL database
	@echo "$(RED)Dropping MySQL database...$(NC)"
	@mysql -u root -p -e "DROP DATABASE IF EXISTS {{.ProjectName}}_db;"

.PHONY: db-reset
db-reset: db-drop db-create ## Reset MySQL database
{{else if eq .Database.ID "sqlite"}}.PHONY: db-create
db-create: ## Create SQLite database file
	@echo "$(YELLOW)SQLite database will be created automatically$(NC)"

.PHONY: db-clean
db-clean: ## Remove SQLite database file
	@echo "$(RED)Removing SQLite database...$(NC)"
	@rm -f {{.ProjectName}}.db
{{end}}{{end}}

# Docker targets
{{if .HasFeature "docker"}}.PHONY: docker-build
docker-build: ## Build Docker image
	@echo "$(YELLOW)Building Docker image...$(NC)"
	@docker build -t $(BINARY_NAME):latest .
	@echo "$(GREEN)Docker image built: $(BINARY_NAME):latest$(NC)"

.PHONY: docker-run
docker-run: ## Run Docker container
	@echo "$(YELLOW)Running Docker container...$(NC)"
	@docker run --rm -p 8080:8080 $(BINARY_NAME):latest

.PHONY: docker-compose-up
docker-compose-up: ## Start services with docker-compose
	@echo "$(YELLOW)Starting services with docker-compose...$(NC)"
	@docker-compose up -d
	@echo "$(GREEN)Services started$(NC)"

.PHONY: docker-compose-down
docker-compose-down: ## Stop services with docker-compose
	@echo "$(YELLOW)Stopping services with docker-compose...$(NC)"
	@docker-compose down
	@echo "$(GREEN)Services stopped$(NC)"

.PHONY: docker-compose-logs
docker-compose-logs: ## View docker-compose logs
	@docker-compose logs -f
{{end}}

# Utility targets
.PHONY: clean
clean: ## Clean build artifacts
	@echo "$(YELLOW)Cleaning build artifacts...$(NC)"
	@rm -rf $(BUILD_DIR)
	@rm -f coverage.out coverage.html
	@go clean -cache
	@echo "$(GREEN)Clean completed$(NC)"

.PHONY: deps
deps: ## Download dependencies
	@echo "$(YELLOW)Downloading dependencies...$(NC)"
	@go mod download
	@echo "$(GREEN)Dependencies downloaded$(NC)"

.PHONY: tools
tools: ## Install development tools
	@echo "$(YELLOW)Installing development tools...$(NC)"
{{if .HasFeature "air"}}	@go install github.com/cosmtrek/air@latest
{{end}}	@go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
	@echo "$(GREEN)Development tools installed$(NC)"

.PHONY: version
version: ## Show Go version
	@go version

.PHONY: env
env: ## Show Go environment
	@go env

# Release targets
.PHONY: release
release: clean test build ## Build release version
	@echo "$(GREEN)Release build completed$(NC)"

.PHONY: install
install: ## Install the binary to GOPATH/bin
	@echo "$(YELLOW)Installing $(BINARY_NAME)...$(NC)"
	@go install $(MAIN_PATH)
	@echo "$(GREEN)$(BINARY_NAME) installed to $(shell go env GOPATH)/bin$(NC)"

# Cross-compilation targets
.PHONY: build-all
build-all: ## Build for multiple platforms
	@echo "$(YELLOW)Building for multiple platforms...$(NC)"
	@mkdir -p $(BUILD_DIR)
	@GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o $(BUILD_DIR)/$(BINARY_NAME)-linux-amd64 $(MAIN_PATH)
	@GOOS=darwin GOARCH=amd64 go build -ldflags="-w -s" -o $(BUILD_DIR)/$(BINARY_NAME)-darwin-amd64 $(MAIN_PATH)
	@GOOS=darwin GOARCH=arm64 go build -ldflags="-w -s" -o $(BUILD_DIR)/$(BINARY_NAME)-darwin-arm64 $(MAIN_PATH)
	@GOOS=windows GOARCH=amd64 go build -ldflags="-w -s" -o $(BUILD_DIR)/$(BINARY_NAME)-windows-amd64.exe $(MAIN_PATH)
	@echo "$(GREEN)Multi-platform builds completed$(NC)"
